package service;

import database.DBConnection;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.util.Date;

public class DatabaseBackupService {

    public static boolean backupDatabase(File file) {
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(file));
             Connection conn = DBConnection.getConnection()) {

            writer.write("-- INVENTORY ERP SYSTEM DATABASE BACKUP\n");
            writer.write("-- Generated At: " + new Date() + "\n");
            writer.write("-- Generated By: " + (SessionManager.getUsername() != null ? SessionManager.getUsername() : "System") + "\n\n");
            writer.write("CREATE DATABASE IF NOT EXISTS inventory_db;\n");
            writer.write("USE inventory_db;\n\n");

            backupTable(conn, writer, "users");
            backupTable(conn, writer, "products");
            backupTable(conn, writer, "sales");
            backupTable(conn, writer, "activity_logs");
            backupTable(conn, writer, "categories");
            backupTable(conn, writer, "restock_requests");

            LoggerService.log(SessionManager.getUsername(), "Database backed up successfully to: " + file.getName());
            return true;
        } catch (Exception e) {
            System.err.println("Database backup failed!");
            e.printStackTrace();
            return false;
        }
    }

    private static void backupTable(Connection conn, BufferedWriter writer, String tableName) throws Exception {
        writer.write("-- ------------------------------------------------------\n");
        writer.write("-- Table structure and data for table `" + tableName + "`\n");
        writer.write("-- ------------------------------------------------------\n\n");

        String sql = "SELECT * FROM " + tableName;
        try (Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery(sql)) {

            ResultSetMetaData meta = rs.getMetaData();
            int colCount = meta.getColumnCount();

            // Disable foreign keys temporarily
            writer.write("SET FOREIGN_KEY_CHECKS = 0;\n");
            writer.write("TRUNCATE TABLE `" + tableName + "`;\n");

            int rowCount = 0;
            while (rs.next()) {
                StringBuilder sb = new StringBuilder();
                sb.append("INSERT INTO `").append(tableName).append("` (");
                for (int i = 1; i <= colCount; i++) {
                    sb.append("`").append(meta.getColumnName(i)).append("`").append(i == colCount ? "" : ", ");
                }
                sb.append(") VALUES (");
                for (int i = 1; i <= colCount; i++) {
                    Object val = rs.getObject(i);
                    if (val == null) {
                        sb.append("NULL");
                    } else if (val instanceof Number) {
                        sb.append(val);
                    } else {
                        // Escape single quotes and backslashes for safe SQL insertion
                        String str = val.toString().replace("\\", "\\\\").replace("'", "\\'");
                        sb.append("'").append(str).append("'");
                    }
                    sb.append(i == colCount ? "" : ", ");
                }
                sb.append(");\n");
                writer.write(sb.toString());
                rowCount++;
            }
            
            writer.write("SET FOREIGN_KEY_CHECKS = 1;\n\n");
            System.out.println("Backed up " + rowCount + " rows from table `" + tableName + "`");
        }
    }

    public static boolean restoreDatabase(File file) {
        try (java.io.BufferedReader reader = new java.io.BufferedReader(new java.io.FileReader(file));
             Connection conn = DBConnection.getConnection();
             Statement stmt = conn.createStatement()) {

            StringBuilder sb = new StringBuilder();
            String line;
            while ((line = reader.readLine()) != null) {
                if (line.trim().startsWith("--") || line.trim().startsWith("#") || line.trim().isEmpty()) {
                    continue;
                }
                sb.append(line);
                if (line.trim().endsWith(";")) {
                    String query = sb.toString().trim();
                    if (query.endsWith(";")) {
                        query = query.substring(0, query.length() - 1);
                    }
                    try {
                        stmt.execute(query);
                    } catch (Exception ex) {
                        System.err.println("Error executing: " + query);
                        ex.printStackTrace();
                    }
                    sb.setLength(0);
                }
            }

            LoggerService.log(SessionManager.getUsername(), "Database restored successfully from: " + file.getName());
            return true;
        } catch (Exception e) {
            System.err.println("Database restore failed!");
            e.printStackTrace();
            return false;
        }
    }
}
